import os
import time
import requests
import concurrent.futures


img_urls = ['https://unsplash.com/photos/llGiAyYthDw',
 'https://unsplash.com/photos/lb9hi0NDjT0',
 'https://unsplash.com/photos/8GR8_rAKav4',
 'https://unsplash.com/photos/OtT--E_vtyo',
 'https://unsplash.com/photos/cOQIcSUJ70Q',
 'https://unsplash.com/photos/d2w-_1LJioQ',
 'https://unsplash.com/photos/kLfkVa_4aXM',
 'https://unsplash.com/photos/SdzvgKsVD7o',
 'https://unsplash.com/photos/DXJeM0A_NWA',
 'https://unsplash.com/photos/ZU_PeZd2qYQ',
 'https://unsplash.com/photos/Eh4sTBEG17w',
 'https://unsplash.com/photos/N8Q3qj6h6_I',
 'https://unsplash.com/photos/kCpxfBlxfF4',
 'https://unsplash.com/photos/pRI5JzioTzY',
 'https://unsplash.com/photos/M7GXRoLu-ZM',
 'https://unsplash.com/photos/Ebb8fe-NZtM',
 'https://unsplash.com/photos/birTUenpa1U',
 'https://unsplash.com/photos/Wzici4apto8',
 'https://unsplash.com/photos/H_mdVe5llXo',
 'https://unsplash.com/photos/PPr8Vo_zaM8',
 'https://unsplash.com/photos/gUvHTfxR_RI',
 'https://unsplash.com/photos/g6WdOXX9kG8',
 'https://unsplash.com/photos/RZcwX9khjVg',
 'https://unsplash.com/photos/Hugv8IYAp8Y',
 'https://unsplash.com/photos/kUazHBZuenA',
 'https://unsplash.com/photos/AKusNjhccYw',
 'https://unsplash.com/photos/6D7txF1rlqQ',
 'https://unsplash.com/photos/SpTF77mWv7Q',
 'https://unsplash.com/photos/c5YQC3LnWSs',
 'https://unsplash.com/photos/YHwvwWBfZcs',
 'https://unsplash.com/photos/ox2w1FZ-Pw0',
 'https://unsplash.com/photos/Xh8Vl0e_W1o',
 'https://unsplash.com/photos/Gp0KJ0X93uw',
 'https://unsplash.com/photos/VW53iOpTaLc',
 'https://unsplash.com/photos/7a21npm1nLY',
 'https://unsplash.com/photos/tXKBcb_jqrA',
 'https://unsplash.com/photos/OutjTIoFNUY',
 'https://unsplash.com/photos/xyt1mxP70oI',
 'https://unsplash.com/photos/wxC0FI6jMHs',
 'https://unsplash.com/photos/aEnsCb6dKlY',
 'https://unsplash.com/photos/jdunGbUGKMA',
 'https://unsplash.com/photos/kIp7VjWk9lQ',
 'https://unsplash.com/photos/9pdcfEo6124',
 'https://unsplash.com/photos/0ZeujkZydok',
 'https://unsplash.com/photos/4pdI5TxqPlQ',
 'https://unsplash.com/photos/m8NYo2IU_Ic',
 'https://unsplash.com/photos/7LBiGYFEfqA',
 'https://unsplash.com/photos/YHyXDbOsqJ4',
 'https://unsplash.com/photos/UkQoBiQ9Ipg',
 'https://unsplash.com/photos/t6zKMAnnmrY',
 'https://unsplash.com/photos/FMn_3ilHYTw',
 'https://unsplash.com/photos/wYp2YG1DwPM',
 'https://unsplash.com/photos/p8gtqJqIGcM',
 'https://unsplash.com/photos/yIdEANRv3no',
 'https://unsplash.com/photos/D8yv3j37S9Y',
 'https://unsplash.com/photos/gSWmKeb7MMs',
 'https://unsplash.com/photos/7Kti8iT3bjg',
 'https://unsplash.com/photos/YGAOoWRWVR4',
 'https://unsplash.com/photos/6KisTpSle8Q',
 'https://unsplash.com/photos/GXu6tlNHeSk',
 'https://unsplash.com/photos/FXNHHD9GEOE',
 'https://unsplash.com/photos/ib95PInlg6E',
 'https://unsplash.com/photos/UaB91-kVLb4',
 'https://unsplash.com/photos/virGC80Qgcw',
 'https://unsplash.com/photos/ICTKcvnXx_8',
 'https://unsplash.com/photos/ZZ4KpYW86Ms',
 'https://unsplash.com/photos/4eNuCoKHc34',
 'https://unsplash.com/photos/chmE8NgEAnk',
 'https://unsplash.com/photos/sjkwqZM3nCs',
 'https://unsplash.com/photos/8pb7Hq539Zw',
 'https://unsplash.com/photos/3JTbarf3Xd0',
 'https://unsplash.com/photos/2c2Bt2kDefk',
 'https://unsplash.com/photos/L2iZFRPaH1M',
 'https://unsplash.com/photos/otG_xXS30xU',
 'https://unsplash.com/photos/HkQgF3jP4A8',
 'https://unsplash.com/photos/ZJV_jvwRbbA',
 'https://unsplash.com/photos/ppA3s-68oEg',
 'https://unsplash.com/photos/3-HB37ouRp0',
 'https://unsplash.com/photos/xAlPg9wIRFM',
 'https://unsplash.com/photos/4TBSG2Oqu0Q',
 'https://unsplash.com/photos/b7HB_lqRW9c',
 'https://unsplash.com/photos/6GZXrAFH5E8',
 'https://unsplash.com/photos/xo3fdXgTJP8',
 'https://unsplash.com/photos/q3ZzB3kLX0s',
 'https://unsplash.com/photos/XbLcIXk3qpw',
 'https://unsplash.com/photos/jI3DFouQWHo',
 'https://unsplash.com/photos/r716RSFGNe8',
 'https://unsplash.com/photos/akRHyXErqX0',
 'https://unsplash.com/photos/ZB9pG1cK79o',
 'https://unsplash.com/photos/hiHL_muScoo',
 'https://unsplash.com/photos/y3xWINTPc2Q',
 'https://unsplash.com/photos/6tuH8d6WJlo',
 'https://unsplash.com/photos/z2yNnYMKQiU',
 'https://unsplash.com/photos/5PBV0QssNfA',
 'https://unsplash.com/photos/n0nbOyb2XcE',
 'https://unsplash.com/photos/Xc-Da7mzw7A',
 'https://unsplash.com/photos/oW0OPV8a57k',
 'https://unsplash.com/photos/9iDizfMiiaA',
 'https://unsplash.com/photos/xdubCpvdv6c',
 'https://unsplash.com/photos/90-3E_2KVJk',
 'https://unsplash.com/photos/wvz0Pi14Rzs',
 'https://unsplash.com/photos/PfQIG063sVQ',
 'https://unsplash.com/photos/k0qVvW46yLI',
 'https://unsplash.com/photos/yNvVnPcurD8',
 'https://unsplash.com/photos/flpoEnO7xAQ',
 'https://unsplash.com/photos/fUvziNhy2ho',
 'https://unsplash.com/photos/BbSBf5uv50A',
 'https://unsplash.com/photos/n7MlT7PYV_c',
 'https://unsplash.com/photos/uRxAhK7RgWw',
 'https://unsplash.com/photos/8MDMhlDh-fU',
 'https://unsplash.com/photos/3xf07twcxsY',
 'https://unsplash.com/photos/QJRBfOiweM4',
 'https://unsplash.com/photos/aWwHiNge2c4',
 'https://unsplash.com/photos/BlZTg4f2Kj4',
 'https://unsplash.com/photos/tccTcNPdkNA',
 'https://unsplash.com/photos/dJcMnu9kRHs',
 'https://unsplash.com/photos/0EzYqMaAOSk',
 'https://unsplash.com/photos/v9FQR4tbIq8',
 'https://unsplash.com/photos/LATyAvLH2EA',
 'https://unsplash.com/photos/rcyBua5TB_A',
 'https://unsplash.com/photos/ZowE4-cmJsw',
 'https://unsplash.com/photos/0_B_wiV6DUg',
 'https://unsplash.com/photos/a-tAVmo3yA4',
 'https://unsplash.com/photos/HfhNRdqa9FA',
 'https://unsplash.com/photos/xc2AoKTF6rM',
 'https://unsplash.com/photos/o0j89X4b5BM',
 'https://unsplash.com/photos/14-n8gg4Bzk',
 'https://unsplash.com/photos/ZiI9aNqujp8',
 'https://unsplash.com/photos/CTflmHHVrBM',
 'https://unsplash.com/photos/PSYlFHo8oKA',
 'https://unsplash.com/photos/0zElpJddzts',
 'https://unsplash.com/photos/qZbkhI69ZuM']
url_api = 'https://source.unsplash.com/random'
start = time.time()
save_dir = 'Images'

def download_image(img_url):
    code = img_url.split('/')[4]
    img_url = url_api.replace('random', code)
    img_bytes = requests.get(img_url).content
    img_name = f"{code}.jpg"

    with open(os.path.join(save_dir, img_name), 'wb') as img_file:
        img_file.write(img_bytes)
        print(f"{img_name} downloaded ")


with concurrent.futures.ThreadPoolExecutor() as executor:
    executor.map(download_image, img_urls)


end = time.time()

print(f'Total time elapsed: {end-start} seconds')

